version: 2
registries:
  npm:
    type: npm-registry
    url: https://registry.npmjs.org
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    registries:
      - npm
    schedule:
      interval: 'weekly'
    labels:
      - 'dependencies'
