policy:
  approval:
    - or:
        - dependabot doing security fix
        - gha doing bump version
        - gha doing merge back after release
  disapproval:
    requires:
      organizations:
        - hk01-digital
approval_rules:
  - name: dependabot doing security fix
    if:
      only_changed_files:
        paths:
          - package.json
          - package-lock.json
          - yarn.lock
      has_author_in:
        users:
          - dependabot[bot]
      only_has_contributors_in:
        users:
          - dependabot[bot]
      targets_branch:
        pattern: development
    requires:
      count: 0
  - name: gha doing bump version
    if:
      only_changed_files:
        paths:
          - package.json
          - package-lock.json
          - yarn.lock
          - CHANGELOG.md
      has_author_in:
        users:
          - github-actions[bot]
    requires:
      count: 0
  - name: gha doing merge back after release
    if:
      has_author_in:
        users:
          - github-actions[bot]
      targets_branch:
        pattern: development
    requires:
      count: 0
