name: Read Changelog
description: 'Read changelog'
outputs:
  LATEST_CHANGELOG:
    description: 'Changelog content'
    value: ${{ steps.read_changelog.outputs.LATEST_CHANGELOG }}
runs:
  using: "composite"
  steps:
    - name: Read Changelog
      id: read_changelog
      shell: bash
      run: |
        # Extract the latest changelog entry
        LATEST_CHANGELOG=$(awk '/^## /{if (flag) exit; flag=1} flag' CHANGELOG.md | sed 's/"/\\"/g')

        # output the release notes
        echo "LATEST_CHANGELOG<<EOF" >> $GITHUB_OUTPUT
        echo "$LATEST_CHANGELOG" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT
