name: Tag Version
description: 'Get version number from package.json'
outputs:
  TAG:
    description: 'Tag version'
    value: ${{ steps.tag_version.outputs.TAG }}
runs:
  using: "composite"
  steps:
    - name: Tag Version
      id: tag_version
      shell: bash
      run: |
        git branch -a
        git checkout -qf master
        git fetch --all
        git pull

        TAG="v$(jq -r .version package.json)"
        echo "TAG=$TAG" >> $GITHUB_OUTPUT
        git tag $TAG
        git push origin $TAG
