name: Post Release
on:
  workflow_dispatch:
env:
  GH_TOKEN: ${{ github.token }}
jobs:
  main:
    runs-on: ['ubuntu-latest']
    steps:
      - uses: actions/checkout@v4

      - name: Check github variables
        run: |
          echo "github.base_ref: ${{ github.base_ref }}"
          echo "github.head_ref: ${{ github.ref_name }}"

      # - name: Read Changelog
      #   id: read_changelog
      #   uses: ./.github/actions/read-changelog

      # - name: Tag version
      #   id: tag_version
      #   uses: ./.github/actions/tag-version

      # - name: Show Output Vars
      #   run: |
      #     echo "TAG: ${{ steps.tag_version.outputs.TAG }}"
      #     echo "LATEST_CHANGELOG: ${{ steps.read_changelog.outputs.LATEST_CHANGELOG }}"

      # - name: Create GitHub Release
      #   uses: ncipollo/release-action@v1
      #   with:
      #     tag: ${{ steps.tag_version.outputs.TAG }}
      #     name: ${{ steps.tag_version.outputs.TAG }}
      #     body: ${{ steps.read_changelog.outputs.LATEST_CHANGELOG }}
      #     draft: false
      #     prerelease: false
      #     skipIfReleaseExists: true
      #     token: ${{ env.GH_TOKEN}}

      # - name: Create merge back
      #   env:
      #     GH_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
      #   uses: ./.github/actions/create-merge-back
      #   with:
      #     environment: 'production'
