name: Post Release
on:
  workflow_dispatch:
env:
  GH_TOKEN: ${{ github.token }}
jobs:
  main:
    runs-on: ['ubuntu-latest']
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Tag version
        run: |
          git checkout -qf master
          git fetch --all
          git pull

          TAG="v$(jq -r .version package.json)"
          echo "TAG=$TAG" >> $GITHUB_ENV
          git tag $TAG
          git push origin $TAG

      - name: Read Changelog and Create Release Notes
        id: create_release_notes
        run: |
          # Extract the latest changelog entry
          LATEST_CHANGELOG=$(awk '/^## \[/{if (flag) exit; flag=1; next} flag' CHANGELOG.md)
          echo "LATEST_CHANGELOG:"
          echo "$LATEST_CHANGELOG"

          # Create the release notes
          echo "LATEST_CHANGELOG=$LATEST_CHANGELOG" >> GITHUB_OUTPUT

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ env.TAG }}
          name: ${{ env.TAG }}
          body: ${{ steps.create_release_notes.outputs.LATEST_CHANGELOG }}
          draft: false
          prerelease: false
          skipIfReleaseExists: true
          token: ${{ env.GH_TOKEN}}
